spring:
    application:
        name: innerjoin
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${MYSQL_PASSWORD}
        url: ${MYSQL_URL}
        username: ${MYSQL_USERNAME}



    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                default_batch_fetch_size: 500
                format_sql: true

    mail:
        host: smtp.gmail.com
        port: 587 # 2
        username: ${MAIL_USERNAME} # 3
        password: ${MAIL_PASSWORD} # 4
        properties:
            mail:
                smtp:
                    auth: true # 5
                    timeout: 5000 # 6
                    starttls:
                        enable: true # 7

server:
    servlet:
        session:
            timeout: 30m

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true

azure:
    blob:
        connection-string: ${CONNECTION_STRING}
        container-name: innerjoin-img

univcert:
    api-key: ${UNIV_CERT_API_KEY}
    univ-check: true # true: 재학 여부 확인, false: 메일 소유자 인증