spring:
    application:
        name: innerjoin
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${MYSQL_PASSWORD}
        url: ${MYSQL_URL}
        username: ${MYSQL_USERNAME}

    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                default_batch_fetch_size: 500
                format_sql: true
