# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  - group: innerjoin-cicd # 변수 그룹 사용

jobs:
  - job: DeployToVM
    pool:
      name: 'Default'
      demands:
        - agent.name -equals inner-join-WAS  # 에이전트 이름
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(AZURE_SUBSCRIPTION_ID)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az storage blob download \
              --account-name $(AZURE_STORAGE_NAME) \
              --container-name $(AZURE_CONTAINER_NAME) \
              --name $(filename) \
              --file $(System.DefaultWorkingDirectory)/$(filename)
          displayName: 'Download Blob from Azure Storage'

      # Step 2: 파일 압축 해제
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: '$(System.DefaultWorkingDirectory)/repository.zip'
          destinationFolder: '/home/innerjoin/deployment'
          cleanDestinationFolder: true

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'rm -f $(System.DefaultWorkingDirectory)/repository.zip'


      - script: |
          # 쉘 스크립트 실행 (VM 내에서 파일이 이미 저장된 경로로 지정)
          bash /home/innerjoin/deployment/script/stop.sh
        displayName: 'Execute stop.sh on VM'

      - script: |
          # 또 다른 쉘 스크립트 실행
          bash /home/innerjoin/deployment/script/start.sh
        displayName: 'Execute start.sh on VM'